# Site settings
title: TheHumanTaurch @ DBC
email: sarah.taurchini@gmail.com
description: "Chronicling the adventures of our fearless heroine on her quest to become the ultimate developer."
baseurl: ""
url: "http://thehumantaurch.github.io/"
twitter_username: the_humantaurch
github_username:  thehumantaurch

# Build settings
markdown: kramdown
permalink: pretty
