name: The Human Taurch
description: Making things
url: http://thehumantaurch.github.io/
markdown: redcarpet
paginate: 5
highlighter: pygments

rss-feed-limit: 10

# disqus-id: yourusername
twitter: the_humantaurch
github: thehumantaurch
# google: +yourusername

permalink: /:title